language: python
python:
    - "2.7"
before_install:
    - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgeos-c1 libgeos-dev
    - sudo apt-get install -qq postgresql-9.1-postgis-2.0
before_script:
   - psql -c 'CREATE DATABASE test_clusterit;' -U postgres
   - psql -d test_clusterit -c "CREATE EXTENSION postgis;" -U postgres
env:
    global:
        - CLUSTERIT_SETTINGS_MODULE=tests.settings
    matrix:
        - TOX_ENV=py27
        - TOX_ENV=py33
        - TOX_ENV=py34
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
branches:
    only:
        - master
        - develop
        - /^feature\/.*$/
        - /^hotfix\/.*$/
        - /^support\/.*$/

